### PR TITLE
Fix LangChainOpenAIHandler for Azure

### LINKED ISSUE #1101: LangChainOpenAIHandler fails with Azure
> return self._chat.invoke(input = messages, model=model, temperature=temperature, deployment_name=self.deployment_id)
>            ^^^^^^^^^^^^^^^^^
> AttributeError: 'functools.partial' object has no attribute 'invoke'

[code](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/algo/ai_handlers/langchain_ai_handler.py#L49)

May have broke from changes by #950

### PR DESCRIPTION
**Pull request by MarkRx**
### **User description**
Refactored to support delayed ChatOpenAI instantiation for Azure

Fixes #1101

___

### **PR Type**
Enhancement, Bug fix

___

### **Description**
- Refactored `LangChainOpenAIHandler` to improve Azure support and efficiency:
  - Introduced a new `_get_chat` method with `@functools.cache` for lazy and efficient chat instance creation
  - Updated `chat` method to use the new `_get_chat` method, supporting delayed `ChatOpenAI` instantiation
  - Removed initialization of `_chat` in the constructor and added early validation
- Updated LangChain dependencies in `requirements.txt`:
  - Upgraded langchain to version 0.2.0
  - Added new dependencies: langchain-core 0.2.28 and langchain-openai 0.1.20
- These changes improve the handling of Azure OpenAI deployments and ensure compatibility with the latest LangChain versions

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>langchain_ai_handler.py</strong><dd><code>Refactor LangChainOpenAIHandler for Azure support</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

pr_agent/algo/ai_handlers/langchain_ai_handler.py

<li>Refactored <code>LangChainOpenAIHandler</code> to support delayed <code>ChatOpenAI</code> <br>instantiation for Azure<br> <li> Introduced a new <code>_get_chat</code> method with <code>@functools.cache</code> for efficient <br>chat instance creation<br> <li> Updated <code>chat</code> method to use the new <code>_get_chat</code> method<br> <li> Removed initialization of <code>_chat</code> in the constructor and added early <br>validation<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1102/files#diff-7f2ff0d6468c62685f01a78c902ad6eb88af711872cf957f61710193db304456">+31/-27</a>&nbsp; </td>

</tr>                    
</table></td></tr><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>requirements.txt</strong><dd><code>Update LangChain dependencies</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

requirements.txt

<li>Updated langchain dependency to version 0.2.0<br> <li> Added new dependencies: langchain-core 0.2.28 and langchain-openai <br>0.1.20<br>

</details>

  </td>
  <td><a href="https://github.com/Codium-ai/pr-agent/pull/1102/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552">+3/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Review by mrT23 — APPROVED** [review]

File: pr_agent/algo/ai_handlers/langchain_ai_handler.py [hunk 1]
```diff
@@ -71,3 +49,29 @@ async def chat_completion(self, model: str, system: str, user: str, temperature:
         except (Exception) as e:
             get_logger().error("Unknown error during OpenAI inference: ", e)
             raise e
+    
+    @functools.cache
+    def _get_chat(self, deployment_id = None):
```
Comment (mrT23) [inline pr_agent/algo/ai_handlers/langchain_ai_handler.py:54]: can you explain these lines ?
why do we need cache ? does it actually work in real deployments? 

i would recommend removing the catch line. Seems like a false optimization to me, since I don't see a use case where it would actually work

**Comment by Nichebiche** [comment]
> _PR-Agent was enabled for this repository. To continue using it, please link your git user with your CodiumAI identity [here](https://app.codium.ai/pr-agent)._
> 
> ## PR Reviewer Guide 🔍
> 
> <table>
> <tr><td>⏱️&nbsp;<strong>Estimated effort to review</strong>: 2 🔵🔵⚪⚪⚪</td></tr>
> <tr><td>🏅&nbsp;<strong>Score</strong>: 92</td></tr>
> <tr><td>🧪&nbsp;<strong>No relevant tests</strong></td></tr>
> <tr><td>🔒&nbsp;<strong>No security concerns identified</strong></td></tr>
> <tr><td>🔀 <strong>Multiple PR themes</strong><br><br>
> 
> <details><summary>
> Sub-PR theme: <b>Refactor LangChainOpenAIHandler for improved Azure support
> </b></summary>
> 
> ___
> 
> Relevant files:
> 
> - pr_agent/algo/ai_handlers/langchain_ai_handler.py
> ___
> 
> </details>
> 
> <details><summary>
> Sub-PR theme: <b>Update LangChain dependencies
> </b></summary>
> 
> ___
> 
> Relevant files:
> 
> - requirements.txt
> ___
> 
> </details>
> 
> </td></tr>
> <tr><td>⚡&nbsp;<strong>Key issues to review</strong><br><br>
> 
> <a href='https://github.com/Codium-ai/pr-agent/pull/1102/files#diff-7f2ff0d6468c62685f01a78c902ad6eb88af711872cf957f61710193db304456R54-R76'><strong>Error Handling</strong></a><br>The new _get_chat method might benefit from more specific error handling, especially for network-related issues when interacting with Azure or OpenAI APIs.
> 
> </td></tr>
> </table>
>

File: pr_agent/algo/ai_handlers/langchain_ai_handler.py (hunk 1 above)
Comment (MarkRx) [reply pr_agent/algo/ai_handlers/langchain_ai_handler.py:54]: It was a quick way to ensure a single chat object existed per LLM deployment. I assumed chat initialization and first use could have some I/O overhead though thinking more about it I agree I'll remove it.

**Review by mrT23 — APPROVED** [review]
