### ISSUE TITLE
LangChainOpenAIHandler fails with Azure

### ISSUE THREAD

**Issue by MarkRx** [Codium-ai/pr-agent#1101]
> return self._chat.invoke(input = messages, model=model, temperature=temperature, deployment_name=self.deployment_id)
>            ^^^^^^^^^^^^^^^^^
> AttributeError: 'functools.partial' object has no attribute 'invoke'

[code](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/algo/ai_handlers/langchain_ai_handler.py#L49)

May have broke from changes by #950
